'use client'

import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { FormEvent,useCallback,useEffect,useState } from 'react'
import { EmptyState,PageHeader,StatusBadge } from '@/components/ui'
import { useSupabase } from '@/lib/supabase/useSupabase'

type ClassRow={id:number;name:string;subject:string|null;join_code:string;archived:boolean;created_at:string}
export default function ClassesPage(){const {user,isLoaded}=useUser();const supabase=useSupabase();const userId=user?.id;const [rows,setRows]=useState<ClassRow[]>([]);const [name,setName]=useState('');const [subject,setSubject]=useState('');const [creating,setCreating]=useState(false);const [message,setMessage]=useState('')
 const load=useCallback(async()=>{if(!userId)return;const r=await supabase.from('classes').select('id,name,subject,join_code,archived,created_at').eq('teacher_id',userId).order('created_at',{ascending:false});if(!r.error)setRows((r.data??[]) as ClassRow[])},[supabase,userId]);useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,load])
 async function create(e:FormEvent){e.preventDefault();if(!userId||!name.trim())return;setCreating(true);setMessage('');const code=crypto.randomUUID().replace(/-/g,'').slice(0,6).toUpperCase();const r=await supabase.from('classes').insert({name:name.trim(),subject:subject.trim()||null,teacher_id:userId,join_code:code}).select('id,name,subject,join_code,archived,created_at').single();setCreating(false);if(r.error)return setMessage(r.error.message);setRows(v=>[r.data as ClassRow,...v]);setName('');setSubject('');setMessage('สร้างห้องเรียนเรียบร้อยแล้ว')}
 return <div className="space-y-7"><PageHeader eyebrow="Classrooms" title="จัดการห้องเรียน" description="สร้างห้อง แชร์รหัสให้นักเรียนเข้าร่วม จัดการสมาชิก และประกาศข่าวสาร"/><section className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:self-start"><h2 className="text-lg font-black">สร้างห้องเรียนใหม่</h2><label className="mt-5 block"><span className="mb-2 block text-sm font-bold">ชื่อห้อง *</span><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5" placeholder="เช่น ปวช.3/1"/></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">รายวิชา</span><input value={subject} onChange={e=>setSubject(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5" placeholder="เช่น โครงงานคอมพิวเตอร์"/></label>{message?<p className="mt-4 rounded-lg bg-orange-50 p-3 text-sm font-bold text-orange-800">{message}</p>:null}<button disabled={creating} className="mt-5 w-full rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-60">{creating?'กำลังสร้าง...':'สร้างห้องเรียน'}</button></form><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">ห้องเรียนของฉัน</h2></div><div className="p-5">{rows.length===0?<EmptyState title="ยังไม่มีห้องเรียน" description="สร้างห้องแรก แล้วแชร์รหัสให้นักเรียนเข้าร่วม"/>:<div className="grid gap-4 md:grid-cols-2">{rows.map(c=><Link key={c.id} href={`/teacher/classes/${c.id}`} className="rounded-xl border border-slate-200 p-4 transition hover:border-orange-300"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-900">{c.name}</h3><p className="mt-1 text-sm text-slate-500">{c.subject||'ไม่ได้ระบุรายวิชา'}</p></div><StatusBadge tone={c.archived?'neutral':'green'}>{c.archived?'เก็บถาวร':'ใช้งาน'}</StatusBadge></div><div className="mt-4 rounded-lg bg-slate-50 p-3"><p className="text-xs font-bold text-slate-400">รหัสเข้าห้อง</p><p className="mt-1 font-mono text-lg font-black tracking-wider text-orange-700">{c.join_code}</p></div></Link>)}</div>}</div></section></section></div>}
