-- check-ngan System: complete production features
-- Adds profile details, class join codes, announcements, notifications,
-- submission/grade history and assignment late-submission control.

alter table public.profiles
  add column if not exists email text,
  add column if not exists avatar_url text,
  add column if not exists level text,
  add column if not exists room text,
  add column if not exists department text,
  add column if not exists major text,
  add column if not exists position text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.classes
  add column if not exists join_code text,
  add column if not exists archived boolean not null default false;

update public.classes
set join_code = upper('C' || lpad(id::text, 5, '0'))
where join_code is null;

alter table public.classes
  alter column join_code set not null;

create unique index if not exists classes_join_code_key on public.classes(join_code);

alter table public.assignments
  add column if not exists allow_late boolean not null default true;

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  teacher_id text not null,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists announcements_class_id_idx on public.announcements(class_id);
create index if not exists announcements_teacher_id_idx on public.announcements(teacher_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  message text,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

create table if not exists public.submission_revisions (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.submissions(id) on delete cascade,
  student_id text not null,
  content text,
  file_path text,
  submitted_at timestamptz not null default now()
);

create index if not exists submission_revisions_submission_idx on public.submission_revisions(submission_id, submitted_at desc);

create table if not exists public.grade_history (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.submissions(id) on delete cascade,
  score numeric not null,
  feedback text,
  graded_by text,
  graded_at timestamptz not null default now()
);

create index if not exists grade_history_submission_idx on public.grade_history(submission_id, graded_at desc);

alter table public.announcements enable row level security;
alter table public.notifications enable row level security;
alter table public.submission_revisions enable row level security;
alter table public.grade_history enable row level security;

-- Profiles: users manage themselves. Teachers may read students in their classes
-- or students who submitted to their assignments. Students may read teachers of joined classes.
drop policy if exists teachers_read_related_student_profiles on public.profiles;
create policy teachers_read_related_student_profiles
on public.profiles for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and role = 'student'
  and (
    exists (
      select 1 from public.class_members cm
      where cm.student_id = profiles.id
        and cm.teacher_id = (select auth.jwt() ->> 'sub')
    )
    or exists (
      select 1
      from public.submissions s
      join public.assignments a on a.id = s.assignment_id
      where s.student_id = profiles.id
        and a.teacher_id = (select auth.jwt() ->> 'sub')
    )
  )
);

drop policy if exists students_read_joined_teacher_profiles on public.profiles;
create policy students_read_joined_teacher_profiles
on public.profiles for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and role = 'teacher'
  and exists (
    select 1 from public.class_members cm
    where cm.student_id = (select auth.jwt() ->> 'sub')
      and cm.teacher_id = profiles.id
  )
);

-- Announcements.
drop policy if exists teachers_manage_own_announcements on public.announcements;
create policy teachers_manage_own_announcements
on public.announcements for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1 from public.classes c
    where c.id = announcements.class_id
      and c.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists students_read_joined_announcements on public.announcements;
create policy students_read_joined_announcements
on public.announcements for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1 from public.class_members cm
    where cm.class_id = announcements.class_id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

-- Notifications.
drop policy if exists users_read_own_notifications on public.notifications;
create policy users_read_own_notifications
on public.notifications for select to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

drop policy if exists users_update_own_notifications on public.notifications;
create policy users_update_own_notifications
on public.notifications for update to authenticated
using (user_id = (select auth.jwt() ->> 'sub'))
with check (user_id = (select auth.jwt() ->> 'sub'));

-- Submission revision history.
drop policy if exists students_read_own_submission_revisions on public.submission_revisions;
create policy students_read_own_submission_revisions
on public.submission_revisions for select to authenticated
using (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
);

drop policy if exists teachers_read_related_submission_revisions on public.submission_revisions;
create policy teachers_read_related_submission_revisions
on public.submission_revisions for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = submission_revisions.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

-- Grade history.
drop policy if exists students_read_own_grade_history on public.grade_history;
create policy students_read_own_grade_history
on public.grade_history for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1 from public.submissions s
    where s.id = grade_history.submission_id
      and s.student_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists teachers_read_related_grade_history on public.grade_history;
create policy teachers_read_related_grade_history
on public.grade_history for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = grade_history.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

-- Allow application clients to read/write the new data through RLS.
grant select, insert, update on public.announcements to authenticated;
grant delete on public.announcements to authenticated;
grant select, update on public.notifications to authenticated;
grant select on public.submission_revisions to authenticated;
grant select on public.grade_history to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Join a class by code without exposing all class rows to students.
create or replace function public.join_class_by_code(p_code text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_class public.classes%rowtype;
  v_user text := auth.jwt() ->> 'sub';
  v_role text := auth.jwt() -> 'metadata' ->> 'role';
begin
  if v_user is null or v_role <> 'student' then
    raise exception 'Only students can join a class';
  end if;

  select * into v_class
  from public.classes
  where upper(join_code) = upper(trim(p_code))
    and archived = false
  limit 1;

  if v_class.id is null then
    raise exception 'Class code not found';
  end if;

  insert into public.class_members(class_id, student_id, teacher_id)
  values (v_class.id, v_user, v_class.teacher_id)
  on conflict (class_id, student_id) do nothing;

  return v_class.id;
end;
$$;

grant execute on function public.join_class_by_code(text) to authenticated;

-- Teacher adds a student using the student's profile code.
create or replace function public.teacher_add_student_by_code(p_class_id bigint, p_student_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher text := auth.jwt() ->> 'sub';
  v_role text := auth.jwt() -> 'metadata' ->> 'role';
  v_student text;
begin
  if v_teacher is null or v_role <> 'teacher' then
    raise exception 'Only teachers can add students';
  end if;

  if not exists (select 1 from public.classes where id = p_class_id and teacher_id = v_teacher) then
    raise exception 'Class not found';
  end if;

  select id into v_student
  from public.profiles
  where role = 'student' and student_id = trim(p_student_code)
  limit 1;

  if v_student is null then
    raise exception 'Student code not found';
  end if;

  insert into public.class_members(class_id, student_id, teacher_id)
  values (p_class_id, v_student, v_teacher)
  on conflict (class_id, student_id) do nothing;

  return v_student;
end;
$$;

grant execute on function public.teacher_add_student_by_code(bigint, text) to authenticated;

-- Automatically capture submission revisions.
create or replace function public.capture_submission_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'submitted' and new.submitted_at is not null
     and (tg_op = 'INSERT' or old.submitted_at is distinct from new.submitted_at) then
    insert into public.submission_revisions(submission_id, student_id, content, file_path, submitted_at)
    values (new.id, new.student_id, new.content, new.file_path, new.submitted_at);
  end if;
  return new;
end;
$$;

drop trigger if exists capture_submission_revision_trigger on public.submissions;
create trigger capture_submission_revision_trigger
after insert or update on public.submissions
for each row execute function public.capture_submission_revision();

-- Automatically capture grade history.
create or replace function public.capture_grade_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.grade_history(submission_id, score, feedback, graded_by, graded_at)
  values (new.submission_id, new.score, new.feedback, new.graded_by, new.graded_at);
  return new;
end;
$$;

drop trigger if exists capture_grade_history_trigger on public.grades;
create trigger capture_grade_history_trigger
after insert or update on public.grades
for each row execute function public.capture_grade_history();

-- Notification helpers and triggers.
create or replace function public.notify_new_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.class_id is not null then
    insert into public.notifications(user_id, title, message, href)
    select cm.student_id, 'มีงานใหม่', new.title, '/student/assignments/' || new.id
    from public.class_members cm
    where cm.class_id = new.class_id;
  end if;
  return new;
end;
$$;

drop trigger if exists notify_new_assignment_trigger on public.assignments;
create trigger notify_new_assignment_trigger
after insert on public.assignments
for each row execute function public.notify_new_assignment();

create or replace function public.notify_new_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher text;
  v_title text;
begin
  if new.status = 'submitted' and new.submitted_at is not null
     and (tg_op = 'INSERT' or old.submitted_at is distinct from new.submitted_at) then
    select a.teacher_id, a.title into v_teacher, v_title
    from public.assignments a where a.id = new.assignment_id;
    if v_teacher is not null then
      insert into public.notifications(user_id, title, message, href)
      values (v_teacher, 'มีนักเรียนส่งงาน', coalesce(v_title, 'งานที่มอบหมาย'), '/teacher/submissions/' || new.id);
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists notify_new_submission_trigger on public.submissions;
create trigger notify_new_submission_trigger
after insert or update on public.submissions
for each row execute function public.notify_new_submission();

create or replace function public.notify_grade_saved()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student text;
  v_assignment bigint;
  v_title text;
begin
  select s.student_id, s.assignment_id into v_student, v_assignment
  from public.submissions s where s.id = new.submission_id;
  select title into v_title from public.assignments where id = v_assignment;
  if v_student is not null then
    insert into public.notifications(user_id, title, message, href)
    values (v_student, 'ตรวจงานแล้ว', coalesce(v_title, 'งานที่ส่ง'), '/student/assignments/' || v_assignment);
  end if;
  return new;
end;
$$;

drop trigger if exists notify_grade_saved_trigger on public.grades;
create trigger notify_grade_saved_trigger
after insert or update on public.grades
for each row execute function public.notify_grade_saved();

create or replace function public.notify_announcement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications(user_id, title, message, href)
  select cm.student_id, 'ประกาศจากอาจารย์', new.title, '/student'
  from public.class_members cm
  where cm.class_id = new.class_id;
  return new;
end;
$$;

drop trigger if exists notify_announcement_trigger on public.announcements;
create trigger notify_announcement_trigger
after insert on public.announcements
for each row execute function public.notify_announcement();
