-- Check Ngan foundation migration
-- IMPORTANT: Configure Clerk as Supabase Third-Party Auth before applying.
-- Clerk session token must include top-level role=authenticated and metadata.role.

begin;

-- Existing profiles table uses Clerk user IDs as text.
alter table public.profiles enable row level security;

-- Existing assignments.teacher_id was UUID, but Clerk user IDs are text (user_...).
alter table public.assignments
  alter column teacher_id type text using teacher_id::text;

alter table public.assignments
  add column if not exists class_id bigint,
  add column if not exists max_score numeric not null default 100 check (max_score >= 0),
  add column if not exists file_path text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.submissions
  add column if not exists content text,
  add column if not exists file_path text,
  add column if not exists submitted_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- Preserve legacy submission detail.
update public.submissions
set content = detail
where content is null and detail is not null;

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  teacher_id text not null default (auth.jwt() ->> 'sub'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.class_members (
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id text not null,
  joined_at timestamptz not null default now(),
  primary key (class_id, student_id)
);

alter table public.assignments
  drop constraint if exists assignments_class_id_fkey;

alter table public.assignments
  add constraint assignments_class_id_fkey
  foreign key (class_id) references public.classes(id) on delete cascade;

create table if not exists public.grades (
  submission_id bigint primary key references public.submissions(id) on delete cascade,
  score numeric not null check (score >= 0),
  feedback text,
  graded_by text,
  graded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Preserve legacy score/feedback before moving grading UI to public.grades.
insert into public.grades (submission_id, score, feedback, graded_by, graded_at)
select id, score, feedback, null, coalesce(created_at, now())
from public.submissions
where score is not null
on conflict (submission_id) do nothing;

create index if not exists classes_teacher_id_idx on public.classes(teacher_id);
create index if not exists class_members_student_id_idx on public.class_members(student_id);
create index if not exists assignments_class_id_idx on public.assignments(class_id);
create index if not exists assignments_teacher_id_idx on public.assignments(teacher_id);
create index if not exists submissions_assignment_id_idx on public.submissions(assignment_id);
create index if not exists submissions_student_id_idx on public.submissions(student_id);

alter table public.classes enable row level security;
alter table public.class_members enable row level security;
alter table public.assignments enable row level security;
alter table public.grades enable row level security;

-- Profiles: user reads/updates only their own profile.
drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
on public.profiles for select to authenticated
using (id = (select auth.jwt() ->> 'sub'));

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles for update to authenticated
using (id = (select auth.jwt() ->> 'sub'))
with check (id = (select auth.jwt() ->> 'sub'));

-- Classes: teachers manage own classes; students read joined classes.
drop policy if exists teachers_manage_own_classes on public.classes;
create policy teachers_manage_own_classes
on public.classes for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
);

drop policy if exists students_read_joined_classes on public.classes;
create policy students_read_joined_classes
on public.classes for select to authenticated
using (
  exists (
    select 1 from public.class_members cm
    where cm.class_id = classes.id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

-- Class memberships.
drop policy if exists teachers_manage_own_class_members on public.class_members;
create policy teachers_manage_own_class_members
on public.class_members for all to authenticated
using (
  exists (
    select 1 from public.classes c
    where c.id = class_members.class_id
      and c.teacher_id = (select auth.jwt() ->> 'sub')
  )
)
with check (
  exists (
    select 1 from public.classes c
    where c.id = class_members.class_id
      and c.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists students_read_own_memberships on public.class_members;
create policy students_read_own_memberships
on public.class_members for select to authenticated
using (student_id = (select auth.jwt() ->> 'sub'));

-- Assignments.
drop policy if exists teachers_manage_own_assignments on public.assignments;
create policy teachers_manage_own_assignments
on public.assignments for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
);

drop policy if exists students_read_class_assignments on public.assignments;
create policy students_read_class_assignments
on public.assignments for select to authenticated
using (
  exists (
    select 1 from public.class_members cm
    where cm.class_id = assignments.class_id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

-- Submissions: remove the old public read policy before enabling RLS.
drop policy if exists "Enable read access for all users" on public.submissions;

drop policy if exists students_read_own_submissions on public.submissions;
create policy students_read_own_submissions
on public.submissions for select to authenticated
using (student_id = (select auth.jwt() ->> 'sub'));

drop policy if exists students_create_own_submissions on public.submissions;
create policy students_create_own_submissions
on public.submissions for insert to authenticated
with check (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1
    from public.assignments a
    join public.class_members cm on cm.class_id = a.class_id
    where a.id = submissions.assignment_id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists students_update_own_submissions on public.submissions;
create policy students_update_own_submissions
on public.submissions for update to authenticated
using (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
)
with check (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
);

drop policy if exists teachers_read_submissions_for_own_assignments on public.submissions;
create policy teachers_read_submissions_for_own_assignments
on public.submissions for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1 from public.assignments a
    where a.id = submissions.assignment_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

alter table public.submissions enable row level security;

-- Grades: students read own; teachers manage grades on their assignments.
drop policy if exists students_read_own_grades on public.grades;
create policy students_read_own_grades
on public.grades for select to authenticated
using (
  exists (
    select 1 from public.submissions s
    where s.id = grades.submission_id
      and s.student_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists teachers_manage_grades_for_own_assignments on public.grades;
create policy teachers_manage_grades_for_own_assignments
on public.grades for all to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = grades.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
)
with check (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = grades.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.classes to authenticated;
grant select, insert, update, delete on public.class_members to authenticated;
grant select, insert, update, delete on public.assignments to authenticated;
grant select, insert, update, delete on public.submissions to authenticated;
grant select, insert, update, delete on public.grades to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
