-- Check Ngan foundation migration
-- Prerequisite: Clerk is configured as Supabase Third-Party Auth.
-- Clerk session tokens must include:
--   role = authenticated
--   metadata.role = teacher | student

-- ---------------------------------------------------------------------------
-- Existing tables: normalize Clerk user IDs and add application columns.
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;

-- Clerk user IDs are strings such as user_xxx, not UUIDs.
alter table public.assignments
  alter column teacher_id type text using teacher_id::text;

alter table public.assignments
  add column if not exists class_id bigint,
  add column if not exists max_score numeric not null default 100 check (max_score >= 0),
  add column if not exists file_path text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.submissions
  add column if not exists content text,
  add column if not exists file_path text,
  add column if not exists submitted_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- Preserve legacy submission text.
update public.submissions
set content = detail
where content is null and detail is not null;

-- ---------------------------------------------------------------------------
-- Core classroom tables.
-- ---------------------------------------------------------------------------

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  teacher_id text not null default (auth.jwt() ->> 'sub'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Needed for composite foreign keys that guarantee the teacher owns the class.
alter table public.classes
  drop constraint if exists classes_id_teacher_id_key;

alter table public.classes
  add constraint classes_id_teacher_id_key unique (id, teacher_id);

create table if not exists public.class_members (
  class_id bigint not null,
  student_id text not null,
  teacher_id text,
  joined_at timestamptz not null default now(),
  primary key (class_id, student_id)
);

-- Backfill teacher_id safely if this migration is re-run after memberships exist.
update public.class_members cm
set teacher_id = c.teacher_id
from public.classes c
where c.id = cm.class_id
  and cm.teacher_id is null;

alter table public.class_members
  alter column teacher_id set not null;

alter table public.class_members
  drop constraint if exists class_members_class_id_fkey,
  drop constraint if exists class_members_class_teacher_fkey;

alter table public.class_members
  add constraint class_members_class_teacher_fkey
  foreign key (class_id, teacher_id)
  references public.classes(id, teacher_id)
  on delete cascade;

-- Assignment must point to a class owned by the same teacher.
alter table public.assignments
  drop constraint if exists assignments_class_id_fkey,
  drop constraint if exists assignments_class_teacher_fkey;

alter table public.assignments
  add constraint assignments_class_teacher_fkey
  foreign key (class_id, teacher_id)
  references public.classes(id, teacher_id)
  on delete cascade;

-- One student has one submission row per assignment. Re-submission updates that row.
alter table public.submissions
  drop constraint if exists submissions_assignment_student_key;

alter table public.submissions
  add constraint submissions_assignment_student_key
  unique (assignment_id, student_id);

create table if not exists public.grades (
  submission_id bigint primary key references public.submissions(id) on delete cascade,
  score numeric not null check (score >= 0),
  feedback text,
  graded_by text default (auth.jwt() ->> 'sub'),
  graded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Preserve legacy score/feedback before grading moves fully to public.grades.
insert into public.grades (submission_id, score, feedback, graded_by, graded_at)
select id, score, feedback, null, coalesce(created_at, now())
from public.submissions
where score is not null
on conflict (submission_id) do nothing;

-- Enforce score <= assignment.max_score at the database layer.
create or replace function public.validate_grade_score()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  assignment_max_score numeric;
begin
  select a.max_score
    into assignment_max_score
  from public.submissions s
  join public.assignments a on a.id = s.assignment_id
  where s.id = new.submission_id;

  if assignment_max_score is null then
    raise exception 'Assignment not found for submission %', new.submission_id;
  end if;

  if new.score < 0 or new.score > assignment_max_score then
    raise exception 'Score must be between 0 and %', assignment_max_score;
  end if;

  return new;
end;
$$;

drop trigger if exists validate_grade_score_trigger on public.grades;
create trigger validate_grade_score_trigger
before insert or update on public.grades
for each row execute function public.validate_grade_score();

-- ---------------------------------------------------------------------------
-- Indexes.
-- ---------------------------------------------------------------------------

create index if not exists classes_teacher_id_idx on public.classes(teacher_id);
create index if not exists class_members_student_id_idx on public.class_members(student_id);
create index if not exists class_members_teacher_id_idx on public.class_members(teacher_id);
create index if not exists assignments_class_id_idx on public.assignments(class_id);
create index if not exists assignments_teacher_id_idx on public.assignments(teacher_id);
create index if not exists submissions_assignment_id_idx on public.submissions(assignment_id);
create index if not exists submissions_student_id_idx on public.submissions(student_id);

-- ---------------------------------------------------------------------------
-- RLS.
-- ---------------------------------------------------------------------------

alter table public.classes enable row level security;
alter table public.class_members enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.grades enable row level security;

-- Profiles: a user manages only their own profile, and profile role must match JWT.
drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
on public.profiles for select to authenticated
using (id = (select auth.jwt() ->> 'sub'));

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles for insert to authenticated
with check (
  id = (select auth.jwt() ->> 'sub')
  and role = (select auth.jwt() -> 'metadata' ->> 'role')
);

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles for update to authenticated
using (id = (select auth.jwt() ->> 'sub'))
with check (
  id = (select auth.jwt() ->> 'sub')
  and role = (select auth.jwt() -> 'metadata' ->> 'role')
);

-- Classes: teacher manages own classes; student reads joined classes.
drop policy if exists teachers_manage_own_classes on public.classes;
create policy teachers_manage_own_classes
on public.classes for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
);

drop policy if exists students_read_joined_classes on public.classes;
create policy students_read_joined_classes
on public.classes for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1
    from public.class_members cm
    where cm.class_id = classes.id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

-- Membership policies intentionally do not query public.classes.
-- This avoids recursive RLS between classes and class_members.
drop policy if exists teachers_manage_own_class_members on public.class_members;
create policy teachers_manage_own_class_members
on public.class_members for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
);

drop policy if exists students_read_own_memberships on public.class_members;
create policy students_read_own_memberships
on public.class_members for select to authenticated
using (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
);

-- Assignments.
drop policy if exists teachers_manage_own_assignments on public.assignments;
create policy teachers_manage_own_assignments
on public.assignments for all to authenticated
using (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
)
with check (
  teacher_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
);

drop policy if exists students_read_class_assignments on public.assignments;
create policy students_read_class_assignments
on public.assignments for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1
    from public.class_members cm
    where cm.class_id = assignments.class_id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

-- Remove legacy unrestricted submission policy.
drop policy if exists "Enable read access for all users" on public.submissions;

drop policy if exists students_read_own_submissions on public.submissions;
create policy students_read_own_submissions
on public.submissions for select to authenticated
using (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
);

drop policy if exists students_create_own_submissions on public.submissions;
create policy students_create_own_submissions
on public.submissions for insert to authenticated
with check (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and status in ('pending', 'submitted')
  and exists (
    select 1
    from public.assignments a
    join public.class_members cm on cm.class_id = a.class_id
    where a.id = submissions.assignment_id
      and cm.student_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists students_update_own_submissions on public.submissions;
create policy students_update_own_submissions
on public.submissions for update to authenticated
using (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
)
with check (
  student_id = (select auth.jwt() ->> 'sub')
  and (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and status in ('pending', 'submitted')
);

drop policy if exists teachers_read_submissions_for_own_assignments on public.submissions;
create policy teachers_read_submissions_for_own_assignments
on public.submissions for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.assignments a
    where a.id = submissions.assignment_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

-- Grades: students read their own; teachers manage grades on their assignments.
drop policy if exists students_read_own_grades on public.grades;
create policy students_read_own_grades
on public.grades for select to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'student'
  and exists (
    select 1
    from public.submissions s
    where s.id = grades.submission_id
      and s.student_id = (select auth.jwt() ->> 'sub')
  )
);

drop policy if exists teachers_manage_grades_for_own_assignments on public.grades;
create policy teachers_manage_grades_for_own_assignments
on public.grades for all to authenticated
using (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = grades.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
)
with check (
  (select auth.jwt() -> 'metadata' ->> 'role') = 'teacher'
  and graded_by = (select auth.jwt() ->> 'sub')
  and exists (
    select 1
    from public.submissions s
    join public.assignments a on a.id = s.assignment_id
    where s.id = grades.submission_id
      and a.teacher_id = (select auth.jwt() ->> 'sub')
  )
);

-- ---------------------------------------------------------------------------
-- Data API privileges. RLS still decides which rows are accessible.
-- ---------------------------------------------------------------------------

grant usage on schema public to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.classes to authenticated;
grant select, insert, update, delete on public.class_members to authenticated;
grant select, insert, update, delete on public.assignments to authenticated;

-- Do not allow authenticated clients to write legacy score/feedback columns.
revoke all on public.submissions from authenticated;
grant select on public.submissions to authenticated;
grant insert (
  assignment_id, student_id, status, title, detail,
  content, file_path, submitted_at, updated_at
) on public.submissions to authenticated;
grant update (
  status, title, detail, content, file_path, submitted_at, updated_at
) on public.submissions to authenticated;

grant select, insert, update, delete on public.grades to authenticated;
grant usage, select on all sequences in schema public to authenticated;
