'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useState } from 'react'
import { EmptyState,PageHeader,SecondaryLink,StatCard,StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Assignment={id:number;title:string;description:string|null;due_date:string|null;max_score:number;class_id:number|null;file_path:string|null;created_at:string|null;updated_at:string|null}
type ClassRow={id:number;name:string;subject:string|null}; type Submission={id:number;student_id:string|null;submitted_at:string|null}
export default function Page(){const {id}=useParams<{id:string}>();const assignmentId=Number(id);const {user,isLoaded}=useUser();const supabase=useSupabase();const userId=user?.id;const [a,setA]=useState<Assignment|null>(null);const [c,setC]=useState<ClassRow|null>(null);const [subs,setSubs]=useState<Submission[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 const load=useCallback(async()=>{if(!userId||!assignmentId)return;setLoading(true);const r=await supabase.from('assignments').select('id,title,description,due_date,max_score,class_id,file_path,created_at,updated_at').eq('id',assignmentId).eq('teacher_id',userId).maybeSingle();if(r.error||!r.data){setError(r.error?.message||'ไม่พบงาน');setLoading(false);return}const row=r.data as Assignment;setA(row);if(row.class_id){const cr=await supabase.from('classes').select('id,name,subject').eq('id',row.class_id).maybeSingle();if(!cr.error)setC((cr.data as ClassRow|null)??null)}const sr=await supabase.from('submissions').select('id,student_id,submitted_at').eq('assignment_id',assignmentId).order('submitted_at',{ascending:false});if(!sr.error)setSubs((sr.data??[]) as Submission[]);setLoading(false)},[assignmentId,supabase,userId]);useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,load]);if(loading)return <div className="rounded-3xl bg-white p-10 text-center">กำลังโหลด...</div>;if(!a)return <div className="space-y-5"><SecondaryLink href="/teacher/assignments">← กลับรายการงาน</SecondaryLink><EmptyState title="เปิดงานไม่ได้" description={error}/></div>
 return <div className="space-y-7"><PageHeader eyebrow="Assignment detail" title={a.title} description="รายละเอียดงานและสถานะการส่ง" actions={<><SecondaryLink href="/teacher/assignments">← รายการงาน</SecondaryLink><Link href={`/teacher/submissions?assignment=${a.id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">ตรวจงาน</Link></>}/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="คะแนนเต็ม" value={a.max_score}/><StatCard label="การส่งงาน" value={subs.length} tone="blue"/><StatCard label="ห้องเรียน" value={c?.name??(a.class_id?`#${a.class_id}`:'-')} tone="orange"/><StatCard label="กำหนดส่ง" value={formatDateTime(a.due_date)} tone="green"/></section><section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><StatusBadge tone="orange">งานที่มอบหมาย</StatusBadge><h2 className="mt-5 font-extrabold">รายละเอียดโจทย์</h2><p className="mt-3 whitespace-pre-wrap rounded-2xl bg-slate-50 p-5 text-sm leading-7 text-slate-700">{a.description||'ไม่มีรายละเอียดเพิ่มเติม'}</p><div className="mt-6 grid gap-4 border-t pt-5 sm:grid-cols-2"><Info label="สร้างเมื่อ" value={formatDateTime(a.created_at)}/><Info label="แก้ไขล่าสุด" value={formatDateTime(a.updated_at)}/><Info label="ห้องเรียน" value={c?`${c.name}${c.subject?` • ${c.subject}`:''}`:'-'}/><Info label="ไฟล์ประกอบ" value={a.file_path?'มีไฟล์':'ไม่ได้แนบไฟล์'}/></div></div><aside className="space-y-4"><div className="rounded-3xl border border-orange-200 bg-orange-50 p-6"><p className="text-xs font-extrabold text-orange-600">SUBMISSIONS</p><p className="mt-3 text-4xl font-extrabold">{subs.length}</p><p className="mt-1 text-sm">งานที่นักเรียนส่งเข้ามา</p><Link href={`/teacher/submissions?assignment=${a.id}`} className="mt-5 inline-flex rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white">ตรวจงานนี้ →</Link></div></aside></section></div>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>}
