'use client'

import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { EmptyState,PageHeader,StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Membership={class_id:number;teacher_id:string;joined_at:string}
type ClassRow={id:number;name:string;subject:string|null;join_code:string;archived:boolean}
type Announcement={id:number;class_id:number;title:string;content:string;created_at:string}
export default function StudentClassesPage(){const {user,isLoaded}=useUser();const supabase=useSupabase();const [memberships,setMemberships]=useState<Membership[]>([]);const [classes,setClasses]=useState<ClassRow[]>([]);const [ann,setAnn]=useState<Announcement[]>([]);const [loading,setLoading]=useState(true)
 const load=useCallback(async()=>{if(!user?.id)return;setLoading(true);const mr=await supabase.from('class_members').select('class_id,teacher_id,joined_at').eq('student_id',user.id).order('joined_at',{ascending:false});const ms=(mr.data??[]) as Membership[];setMemberships(ms);const ids=ms.map(x=>x.class_id);if(ids.length){const cr=await supabase.from('classes').select('id,name,subject,join_code,archived').in('id',ids);setClasses((cr.data??[]) as ClassRow[]);const ar=await supabase.from('announcements').select('id,class_id,title,content,created_at').in('class_id',ids).order('created_at',{ascending:false}).limit(20);setAnn((ar.data??[]) as Announcement[])}else{setClasses([]);setAnn([])}setLoading(false)},[supabase,user?.id]);useEffect(()=>{if(!isLoaded||!user?.id)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,user?.id,load]);const cmap=useMemo(()=>new Map(classes.map(c=>[c.id,c])),[classes])
 return <div className="space-y-7"><PageHeader eyebrow="Classrooms" title="ห้องเรียนของฉัน" description="ดูห้องที่เข้าร่วม รายวิชา และประกาศล่าสุดจากอาจารย์" actions={<Link href="/student/join" className="rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-black text-white">+ เข้าร่วมห้อง</Link>}/><section className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">ห้องเรียนที่เข้าร่วม</h2></div><div className="p-5">{loading?<p className="py-10 text-center text-sm text-slate-500">กำลังโหลด...</p>:memberships.length===0?<EmptyState title="ยังไม่ได้เข้าร่วมห้องเรียน" description="กรอกรหัสห้องที่ได้รับจากอาจารย์เพื่อเริ่มใช้งาน" action={<Link href="/student/join" className="inline-flex rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-black text-white">กรอกรหัสเข้าห้อง</Link>}/>:<div className="grid gap-4 md:grid-cols-2">{memberships.map(m=>{const c=cmap.get(m.class_id);return <div key={m.class_id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{c?.name||`ห้อง #${m.class_id}`}</h3><p className="mt-1 text-sm text-slate-500">{c?.subject||'ไม่ได้ระบุรายวิชา'}</p></div><StatusBadge tone={c?.archived?'neutral':'green'}>{c?.archived?'เก็บถาวร':'กำลังเรียน'}</StatusBadge></div><p className="mt-4 text-xs text-slate-400">เข้าร่วม {formatDateTime(m.joined_at)}</p></div>})}</div>}</div></div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">ประกาศล่าสุด</h2></div><div className="p-5">{ann.length===0?<p className="py-6 text-center text-sm text-slate-500">ยังไม่มีประกาศ</p>:<div className="space-y-3">{ann.map(a=><div key={a.id} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold text-orange-700">{cmap.get(a.class_id)?.name||`ห้อง #${a.class_id}`}</p><h3 className="mt-1 font-black">{a.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{a.content}</p><p className="mt-2 text-xs text-slate-400">{formatDateTime(a.created_at)}</p></div>)}</div>}</div></div></section></div>}
