'use client'

import { useParams } from 'next/navigation'
import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useState } from 'react'
import { EmptyState,PageHeader,SecondaryLink,StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Submission={id:number;assignment_id:number|null;student_id:string|null;content:string|null;file_path:string|null;submitted_at:string|null}
type Assignment={id:number;title:string;description:string|null;max_score:number;due_date:string|null;teacher_id:string|null}
type Grade={submission_id:number;score:number;feedback:string|null;graded_at:string|null}
export default function SubmissionDetail(){const {id}=useParams<{id:string}>();const submissionId=Number(id);const {user,isLoaded}=useUser();const supabase=useSupabase();const userId=user?.id;const [submission,setSubmission]=useState<Submission|null>(null);const [assignment,setAssignment]=useState<Assignment|null>(null);const [grade,setGrade]=useState<Grade|null>(null);const [score,setScore]=useState('');const [feedback,setFeedback]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [fileUrl,setFileUrl]=useState<string|null>(null)
 const load=useCallback(async()=>{if(!userId||!submissionId)return;setLoading(true);const sr=await supabase.from('submissions').select('id,assignment_id,student_id,content,file_path,submitted_at').eq('id',submissionId).maybeSingle();if(sr.error||!sr.data){setSubmission(null);setLoading(false);return}const s=sr.data as Submission;setSubmission(s);if(!s.assignment_id){setLoading(false);return}const ar=await supabase.from('assignments').select('id,title,description,max_score,due_date,teacher_id').eq('id',s.assignment_id).eq('teacher_id',userId).maybeSingle();if(ar.error||!ar.data){setAssignment(null);setLoading(false);return}setAssignment(ar.data as Assignment);const gr=await supabase.from('grades').select('submission_id,score,feedback,graded_at').eq('submission_id',submissionId).maybeSingle();if(!gr.error&&gr.data){const g=gr.data as Grade;setGrade(g);setScore(String(g.score));setFeedback(g.feedback??'')}else{setGrade(null);setScore('');setFeedback('')}setLoading(false)},[submissionId,supabase,userId]);useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,load]);useEffect(()=>{const p=submission?.file_path;if(!p){const t=window.setTimeout(()=>setFileUrl(null),0);return()=>window.clearTimeout(t)}let cancelled=false;void(async()=>{const r=await supabase.storage.from('submissions').createSignedUrl(p,3600);if(!cancelled)setFileUrl(r.data?.signedUrl??null)})();return()=>{cancelled=true}},[submission?.file_path,supabase])
 async function save(){if(!userId||!submission||!assignment)return;const n=Number(score);if(!Number.isFinite(n)||n<0||n>Number(assignment.max_score))return setMessage(`คะแนนต้องอยู่ระหว่าง 0 ถึง ${assignment.max_score}`);setSaving(true);setMessage('');const now=new Date().toISOString();const r=await supabase.from('grades').upsert({submission_id:submission.id,score:n,feedback:feedback.trim()||null,graded_by:userId,graded_at:now,updated_at:now},{onConflict:'submission_id'}).select('submission_id,score,feedback,graded_at').single();setSaving(false);if(r.error)return setMessage(r.error.message);setGrade(r.data as Grade);setMessage('บันทึกคะแนนเรียบร้อยแล้ว')}
 if(loading)return <div className="rounded-3xl bg-white p-10 text-center">กำลังเปิดงาน...</div>;if(!submission||!assignment)return <div className="space-y-5"><SecondaryLink href="/teacher/submissions">← กลับหน้าตรวจงาน</SecondaryLink><EmptyState title="เปิดงานไม่ได้" description="ไม่พบ Submission หรือไม่มีสิทธิ์ตรวจงาน"/></div>
 return <div className="space-y-7"><PageHeader eyebrow="Review submission" title={assignment.title} description={`ตรวจงานของนักเรียน ${submission.student_id||'-'}`} actions={<SecondaryLink href="/teacher/submissions">← กลับหน้าตรวจงาน</SecondaryLink>}/><section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><StatusBadge tone={grade?'green':'orange'}>{grade?'ตรวจแล้ว':'รอการตรวจ'}</StatusBadge><div className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><Info label="นักเรียน" value={submission.student_id||'-'}/><Info label="ส่งเมื่อ" value={formatDateTime(submission.submitted_at)}/><Info label="กำหนดส่ง" value={formatDateTime(assignment.due_date)}/><Info label="คะแนนเต็ม" value={`${assignment.max_score}`}/></div><h2 className="mt-6 font-extrabold">รายละเอียดโจทย์</h2><p className="mt-2 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-sm leading-7">{assignment.description||'ไม่มีรายละเอียด'}</p><h2 className="mt-6 font-extrabold">ข้อความจากนักเรียน</h2><p className="mt-2 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-sm leading-7">{submission.content||'ไม่มีข้อความ'}</p>{fileUrl?<a href={fileUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white">เปิดไฟล์งาน ↗</a>:<p className="mt-5 text-sm text-slate-500">ไม่มีไฟล์แนบ</p>}</div><aside className="rounded-3xl border border-orange-200 bg-white p-6 shadow-sm xl:sticky xl:top-28 xl:self-start"><p className="text-xs font-extrabold text-orange-600">GRADING</p><h2 className="mt-2 text-xl font-extrabold">ให้คะแนนและความคิดเห็น</h2><label className="mt-5 block"><span className="text-sm font-bold">คะแนน</span><div className="mt-2 flex items-center gap-3"><input type="number" min="0" max={assignment.max_score} value={score} onChange={e=>setScore(e.target.value)} className="w-36 rounded-xl border border-slate-200 px-3 py-3 text-lg font-extrabold"/><b>/ {assignment.max_score}</b></div></label><label className="mt-5 block"><span className="text-sm font-bold">ความคิดเห็น</span><textarea rows={7} value={feedback} onChange={e=>setFeedback(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3"/></label>{message?<div className="mt-4 rounded-xl bg-orange-50 p-3 text-sm font-bold text-orange-700">{message}</div>:null}<button onClick={()=>void save()} disabled={saving} className="mt-5 w-full rounded-xl bg-orange-500 px-4 py-3 text-sm font-extrabold text-white">{saving?'กำลังบันทึก...':grade?'บันทึกการแก้ไขคะแนน':'บันทึกคะแนน'}</button></aside></section></div>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-extrabold">{value}</p></div>}
