'use client'

import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { EmptyState,PageHeader,StatCard,StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Assignment={id:number;title:string;max_score:number}
type Submission={id:number;assignment_id:number|null;student_id:string|null;content:string|null;file_path:string|null;submitted_at:string|null}
type Grade={submission_id:number;score:number;feedback:string|null}

export default function TeacherSubmissionsPage(){
 const {user,isLoaded}=useUser();const supabase=useSupabase();const userId=user?.id
 const [assignments,setAssignments]=useState<Assignment[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);const [grades,setGrades]=useState<Grade[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|'waiting'|'graded'>('all');const [assignmentFilter,setAssignmentFilter]=useState('')
 const loadData=useCallback(async()=>{if(!userId)return;setLoading(true);const ar=await supabase.from('assignments').select('id,title,max_score').eq('teacher_id',userId).order('created_at',{ascending:false});if(ar.error){console.error(ar.error);setLoading(false);return}const arows=(ar.data??[]) as Assignment[];setAssignments(arows);const ids=arows.map(a=>a.id);if(!ids.length){setSubmissions([]);setGrades([]);setLoading(false);return}const sr=await supabase.from('submissions').select('id,assignment_id,student_id,content,file_path,submitted_at').in('assignment_id',ids).order('submitted_at',{ascending:false});if(sr.error)console.error(sr.error);const srows=(sr.data??[]) as Submission[];setSubmissions(srows);const sids=srows.map(s=>s.id);if(sids.length){const gr=await supabase.from('grades').select('submission_id,score,feedback').in('submission_id',sids);if(gr.error)console.error(gr.error);setGrades((gr.data??[]) as Grade[])}else setGrades([]);setLoading(false)},[supabase,userId])
 useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void loadData(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,loadData])
 useEffect(()=>{if(!userId)return;const channel=supabase.channel(`teacher-submissions-${userId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'submissions'},()=>void loadData()).subscribe();return()=>{void supabase.removeChannel(channel)}},[supabase,userId,loadData])
 const amap=useMemo(()=>new Map(assignments.map(a=>[a.id,a])),[assignments]);const gmap=useMemo(()=>new Map(grades.map(g=>[g.submission_id,g])),[grades]);const waiting=submissions.filter(s=>!gmap.has(s.id)).length
 const filtered=useMemo(()=>{const k=query.trim().toLowerCase();return submissions.filter(s=>{const a=s.assignment_id?amap.get(s.assignment_id):undefined;const g=gmap.get(s.id);if(filter==='waiting'&&g)return false;if(filter==='graded'&&!g)return false;if(assignmentFilter&&String(s.assignment_id??'')!==assignmentFilter)return false;if(k&&!`${a?.title??''} ${s.student_id??''}`.toLowerCase().includes(k))return false;return true})},[submissions,amap,gmap,filter,assignmentFilter,query])
 return <div className="space-y-7"><PageHeader eyebrow="Submissions" title="ตรวจงานนักเรียน" description="ดูงานที่ส่งเข้ามา เปิดไฟล์ ตรวจคำตอบ และบันทึกคะแนนพร้อมความคิดเห็น" actions={<button onClick={()=>void loadData()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">{loading?'กำลังโหลด...':'รีเฟรช'}</button>}/><section className="grid gap-4 sm:grid-cols-3"><StatCard label="ส่งทั้งหมด" value={submissions.length}/><StatCard label="รอตรวจ" value={waiting} tone="orange"/><StatCard label="ตรวจแล้ว" value={grades.length} tone="green"/></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_220px_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่องานหรือรหัสนักเรียน..." className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/><select value={assignmentFilter} onChange={e=>setAssignmentFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">ทุกงาน</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><div className="flex rounded-xl bg-slate-100 p-1">{(['all','waiting','graded'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} className={`rounded-lg px-3 py-2 text-xs font-extrabold ${filter===v?'bg-white shadow-sm':'text-slate-500'}`}>{v==='all'?'ทั้งหมด':v==='waiting'?'รอตรวจ':'ตรวจแล้ว'}</button>)}</div></div><div className="mt-6">{!loading&&filtered.length===0?<EmptyState title="ยังไม่มีงานในรายการนี้" description="เมื่อนักเรียนส่งงานเข้ามา ระบบจะแสดงที่นี่อัตโนมัติ"/>:<div className="space-y-3">{filtered.map(s=>{const a=s.assignment_id?amap.get(s.assignment_id):undefined;const g=gmap.get(s.id);return <Link key={s.id} href={`/teacher/submissions/${s.id}`} className="group grid gap-4 rounded-2xl border border-slate-200 p-4 hover:border-orange-200 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><div className="flex gap-2"><StatusBadge tone={g?'green':'orange'}>{g?'ตรวจแล้ว':'รอตรวจ'}</StatusBadge>{s.file_path?<StatusBadge tone="blue">มีไฟล์แนบ</StatusBadge>:null}</div><h3 className="mt-2 truncate font-extrabold group-hover:text-orange-600">{a?.title||`งาน #${s.assignment_id??'-'}`}</h3><p className="mt-1 truncate text-sm text-slate-500">นักเรียน: {s.student_id||'-'}</p><p className="mt-1 text-xs text-slate-400">ส่งเมื่อ {formatDateTime(s.submitted_at)}</p></div><div>{g?<p className="text-xl font-extrabold text-emerald-700">{g.score} / {a?.max_score??'-'}</p>:<span className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white">เปิดตรวจงาน →</span>}</div></Link>})}</div>}</div></section></div>
}
