'use client'

import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { EmptyState,PageHeader } from '@/components/ui'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Assignment={id:number;title:string;max_score:number;class_id:number|null}
type Submission={id:number;assignment_id:number|null;student_id:string|null}
type Grade={submission_id:number;score:number}
type Profile={id:string;full_name:string|null;student_id:string|null;level:string|null;room:string|null;major:string|null}
export default function GradebookPage(){const {user,isLoaded}=useUser();const supabase=useSupabase();const [assignments,setAssignments]=useState<Assignment[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);const [grades,setGrades]=useState<Grade[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [assignmentId,setAssignmentId]=useState('')
 const load=useCallback(async()=>{if(!user?.id)return;setLoading(true);const ar=await supabase.from('assignments').select('id,title,max_score,class_id').eq('teacher_id',user.id).order('created_at',{ascending:false});const aa=(ar.data??[]) as Assignment[];setAssignments(aa);const ids=aa.map(a=>a.id);if(!ids.length){setSubmissions([]);setGrades([]);setProfiles([]);setLoading(false);return}const sr=await supabase.from('submissions').select('id,assignment_id,student_id').in('assignment_id',ids);const ss=(sr.data??[]) as Submission[];setSubmissions(ss);const sids=ss.map(s=>s.id);if(sids.length){const gr=await supabase.from('grades').select('submission_id,score').in('submission_id',sids);setGrades((gr.data??[]) as Grade[])}else setGrades([]);const pids=[...new Set(ss.map(s=>s.student_id).filter(Boolean) as string[])];if(pids.length){const pr=await supabase.from('profiles').select('id,full_name,student_id,level,room,major').in('id',pids);setProfiles((pr.data??[]) as Profile[])}else setProfiles([]);setLoading(false)},[supabase,user?.id]);useEffect(()=>{if(!isLoaded||!user?.id)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,user?.id,load]);const pmap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const gmap=useMemo(()=>new Map(grades.map(g=>[g.submission_id,g])),[grades]);const rows=useMemo(()=>submissions.filter(s=>!assignmentId||String(s.assignment_id)===assignmentId).map(s=>{const a=assignments.find(x=>x.id===s.assignment_id);const p=s.student_id?pmap.get(s.student_id):undefined;const g=gmap.get(s.id);return {submission:s,assignment:a,profile:p,grade:g}}),[submissions,assignmentId,assignments,pmap,gmap])
 function exportCsv(){const header=['รหัสนักเรียน','ชื่อ','งาน','คะแนน','คะแนนเต็ม'];const body=rows.map(r=>[r.profile?.student_id||'',r.profile?.full_name||r.submission.student_id||'',r.assignment?.title||'',r.grade?.score??'',r.assignment?.max_score??'']);const csv='\ufeff'+[header,...body].map(cols=>cols.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`check-ngan-gradebook-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="space-y-7"><PageHeader eyebrow="Gradebook" title="สมุดคะแนน" description="ดูคะแนนรวมจากงานที่ตรวจแล้ว และส่งออกข้อมูลเป็น CSV สำหรับเปิดใน Excel" actions={<button onClick={exportCsv} disabled={!rows.length} className="rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">ส่งออก CSV</button>}/><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">รายการคะแนน</h2><p className="mt-1 text-sm text-slate-500">คะแนนจะแสดงเมื่ออาจารย์บันทึกผลการตรวจแล้ว</p></div><select value={assignmentId} onChange={e=>setAssignmentId(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">ทุกงาน</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></div><div className="overflow-x-auto p-5">{loading?<p className="py-10 text-center text-sm text-slate-500">กำลังโหลดสมุดคะแนน...</p>:rows.length===0?<EmptyState title="ยังไม่มีข้อมูลคะแนน" description="เมื่อตรวจงานแล้ว คะแนนจะปรากฏในตารางนี้"/>:<table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-3 py-3">นักเรียน/นักศึกษา</th><th className="px-3 py-3">รหัส</th><th className="px-3 py-3">งาน</th><th className="px-3 py-3 text-right">คะแนน</th><th className="px-3 py-3 text-right">เต็ม</th><th className="px-3 py-3 text-right">เปอร์เซ็นต์</th></tr></thead><tbody>{rows.map(r=>{const score=r.grade?.score;const max=r.assignment?.max_score;const pct=score!=null&&max?Math.round((score/max)*100):null;return <tr key={r.submission.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-3 font-black">{r.profile?.full_name||r.submission.student_id||'-'}</td><td className="px-3 py-3 text-slate-500">{r.profile?.student_id||'-'}</td><td className="px-3 py-3">{r.assignment?.title||'-'}</td><td className="px-3 py-3 text-right font-black">{score??'-'}</td><td className="px-3 py-3 text-right">{max??'-'}</td><td className="px-3 py-3 text-right">{pct==null?'-':`${pct}%`}</td></tr>})}</tbody></table>}</div></section></div>}
