'use client'

import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { useCallback,useEffect,useState } from 'react'
import { EmptyState,PageHeader,StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Row={id:number;title:string;message:string|null;href:string|null;read_at:string|null;created_at:string}
export function NotificationsPage(){const {user,isLoaded}=useUser();const userId=user?.id;const supabase=useSupabase();const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true)
 const load=useCallback(async()=>{if(!userId)return;setLoading(true);const r=await supabase.from('notifications').select('id,title,message,href,read_at,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(100);if(!r.error)setRows((r.data??[]) as Row[]);setLoading(false)},[supabase,userId]);useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,load])
 async function mark(id:number){const now=new Date().toISOString();await supabase.from('notifications').update({read_at:now}).eq('id',id);setRows(v=>v.map(x=>x.id===id?{...x,read_at:now}:x))}
 async function markAll(){if(!userId)return;await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',userId).is('read_at',null);void load()}
 const unread=rows.filter(x=>!x.read_at).length
 return <div className="space-y-7"><PageHeader eyebrow="Notifications" title="ศูนย์แจ้งเตือน" description="งานใหม่ การส่งงาน ผลการตรวจ และประกาศจากห้องเรียนจะรวมอยู่ที่นี่" actions={<button onClick={()=>void markAll()} disabled={!unread} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold disabled:opacity-50">อ่านทั้งหมดแล้ว</button>}/><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><p className="text-sm font-black">ยังไม่ได้อ่าน {unread} รายการ</p></div><div className="p-5">{loading?<p className="py-10 text-center text-sm text-slate-500">กำลังโหลดแจ้งเตือน...</p>:rows.length===0?<EmptyState title="ยังไม่มีการแจ้งเตือน" description="เมื่อมีงานหรือกิจกรรมใหม่ ระบบจะแสดงที่นี่"/>:<div className="divide-y divide-slate-100">{rows.map(n=><div key={n.id} className="flex gap-4 py-4 first:pt-0 last:pb-0"><div className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${n.read_at?'bg-slate-300':'bg-orange-500'}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-900">{n.title}</h3>{!n.read_at?<StatusBadge tone="orange">ใหม่</StatusBadge>:null}</div>{n.message?<p className="mt-1 text-sm text-slate-600">{n.message}</p>:null}<p className="mt-2 text-xs text-slate-400">{formatDateTime(n.created_at)}</p><div className="mt-3 flex gap-2">{n.href?<Link href={n.href} onClick={()=>void mark(n.id)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-black text-white">เปิดรายการ</Link>:null}{!n.read_at?<button onClick={()=>void mark(n.id)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">ทำเครื่องหมายว่าอ่านแล้ว</button>:null}</div></div></div>)}</div>}</div></section></div>}
