'use client'

import { useParams,useRouter } from 'next/navigation'
import { useUser } from '@clerk/nextjs'
import { FormEvent,useCallback,useEffect,useState } from 'react'
import { Breadcrumbs,EmptyState,PageHeader,SecondaryLink } from '@/components/ui'
import { useSupabase } from '@/lib/supabase/useSupabase'

type ClassItem={id:number;name:string;subject:string|null}
type Assignment={id:number;title:string;description:string|null;due_date:string|null;max_score:number;class_id:number|null;allow_late:boolean}
function localDateTime(value:string|null){if(!value)return'';const d=new Date(value);const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)}
export default function EditAssignmentPage(){const {id}=useParams<{id:string}>();const assignmentId=Number(id);const {user,isLoaded}=useUser();const userId=user?.id;const supabase=useSupabase();const router=useRouter();const [classes,setClasses]=useState<ClassItem[]>([]);const [a,setA]=useState<Assignment|null>(null);const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [classId,setClassId]=useState('');const [dueDate,setDueDate]=useState('');const [maxScore,setMaxScore]=useState('');const [allowLate,setAllowLate]=useState(true);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('')
 const load=useCallback(async()=>{if(!userId)return;setLoading(true);const [ar,cr]=await Promise.all([supabase.from('assignments').select('id,title,description,due_date,max_score,class_id,allow_late').eq('id',assignmentId).eq('teacher_id',userId).maybeSingle(),supabase.from('classes').select('id,name,subject').eq('teacher_id',userId).eq('archived',false).order('created_at',{ascending:false})]);const row=(ar.data as Assignment|null)??null;setA(row);setClasses((cr.data??[]) as ClassItem[]);if(row){setTitle(row.title);setDescription(row.description||'');setClassId(row.class_id?String(row.class_id):'');setDueDate(localDateTime(row.due_date));setMaxScore(String(row.max_score));setAllowLate(row.allow_late)}setLoading(false)},[assignmentId,supabase,userId]);useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,load])
 async function submit(e:FormEvent){e.preventDefault();if(!a||!userId)return;const score=Number(maxScore);if(!title.trim()||!classId||!Number.isFinite(score)||score<=0)return setMessage('กรุณากรอกข้อมูลที่จำเป็นให้ถูกต้อง');setSaving(true);setMessage('');const {error}=await supabase.from('assignments').update({title:title.trim(),description:description.trim()||null,class_id:Number(classId),due_date:dueDate?new Date(dueDate).toISOString():null,max_score:score,allow_late:allowLate,updated_at:new Date().toISOString()}).eq('id',a.id).eq('teacher_id',userId);setSaving(false);if(error)return setMessage(error.message);router.push(`/teacher/assignments/${a.id}`);router.refresh()}
 if(loading)return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">กำลังโหลดข้อมูล...</div>;if(!a)return <EmptyState title="เปิดงานไม่ได้" description="ไม่พบงานหรือคุณไม่มีสิทธิ์แก้ไข"/>
 return <div className="space-y-6"><div><Breadcrumbs items={[{label:'ภาพรวม',href:'/teacher'},{label:'งานที่มอบหมาย',href:'/teacher/assignments'},{label:a.title,href:`/teacher/assignments/${a.id}`},{label:'แก้ไข'}]}/><PageHeader eyebrow="Edit assignment" title="แก้ไขงาน" description="ปรับรายละเอียด กำหนดส่ง คะแนนเต็ม และเงื่อนไขการส่ง" actions={<SecondaryLink href={`/teacher/assignments/${a.id}`}>← กลับรายละเอียดงาน</SecondaryLink>}/></div><form onSubmit={submit} className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-5"><Field label="ชื่องาน *"><input value={title} onChange={e=>setTitle(e.target.value)} className="input"/></Field><Field label="ห้องเรียน *"><select value={classId} onChange={e=>setClassId(e.target.value)} className="input"><option value="">-- เลือกห้อง --</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}{c.subject?` • ${c.subject}`:''}</option>)}</select></Field><Field label="รายละเอียด"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={8} className="input"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="กำหนดส่ง"><input type="datetime-local" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="input"/></Field><Field label="คะแนนเต็ม *"><input type="number" min="1" value={maxScore} onChange={e=>setMaxScore(e.target.value)} className="input"/></Field></div><label className="flex gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><input type="checkbox" checked={allowLate} onChange={e=>setAllowLate(e.target.checked)} className="mt-1"/><span><b className="block text-sm">อนุญาตให้ส่งหลังหมดเวลา</b><span className="text-xs text-slate-500">ถ้าปิด ระบบจะไม่รับการส่งใหม่เมื่อเลยกำหนด</span></span></label>{message?<div className="rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{message}</div>:null}<div className="flex justify-end gap-2 border-t border-slate-100 pt-5"><SecondaryLink href={`/teacher/assignments/${a.id}`}>ยกเลิก</SecondaryLink><button disabled={saving} className="rounded-lg bg-orange-600 px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">{saving?'กำลังบันทึก...':'บันทึกการแก้ไข'}</button></div></div></form><style jsx>{`.input{width:100%;border:1px solid rgb(203 213 225);border-radius:.5rem;padding:.75rem;background:white;outline:none}.input:focus{border-color:rgb(251 146 60);box-shadow:0 0 0 2px rgb(255 237 213)}`}</style></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-black">{label}</span>{children}</label>}
