'use client'

import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { EmptyState, PageHeader, PrimaryLink, StatCard, StatusBadge } from '@/components/ui'
import { formatDateTime } from '@/lib/format'
import { useSupabase } from '@/lib/supabase/useSupabase'

type Assignment={id:number;title:string;description:string|null;due_date:string|null;max_score:number;class_id:number|null;created_at:string|null}
type Submission={id:number;assignment_id:number|null}

export default function TeacherAssignmentsPage(){
 const {user,isLoaded}=useUser(); const supabase=useSupabase(); const userId=user?.id
 const [assignments,setAssignments]=useState<Assignment[]>([]); const [submissions,setSubmissions]=useState<Submission[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState('')
 const loadData=useCallback(async()=>{ if(!userId)return; setLoading(true); setError(''); const a=await supabase.from('assignments').select('id,title,description,due_date,max_score,class_id,created_at').eq('teacher_id',userId).order('created_at',{ascending:false}); if(a.error){setError(a.error.message);setLoading(false);return} const rows=(a.data??[]) as Assignment[]; setAssignments(rows); const ids=rows.map(x=>x.id); if(ids.length){const s=await supabase.from('submissions').select('id,assignment_id').in('assignment_id',ids); if(!s.error)setSubmissions((s.data??[]) as Submission[])}else setSubmissions([]); setLoading(false)},[supabase,userId])
 useEffect(()=>{if(!isLoaded||!userId)return;const t=window.setTimeout(()=>void loadData(),0);return()=>window.clearTimeout(t)},[isLoaded,userId,loadData])
 const count=useMemo(()=>{const m=new Map<number,number>();submissions.forEach(s=>{if(s.assignment_id!=null)m.set(s.assignment_id,(m.get(s.assignment_id)??0)+1)});return m},[submissions])
 const filtered=useMemo(()=>{const k=query.trim().toLowerCase();return !k?assignments:assignments.filter(a=>`${a.title} ${a.description??''}`.toLowerCase().includes(k))},[assignments,query])
 return <div className="space-y-7"><PageHeader eyebrow="Assignments" title="งานที่มอบหมาย" description="จัดการงานทั้งหมดที่สร้าง ตรวจสอบกำหนดส่ง และเข้าไปดูงานที่นักเรียนส่ง" actions={<><button onClick={()=>void loadData()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">{loading?'กำลังโหลด...':'รีเฟรช'}</button><PrimaryLink href="/teacher/assignments/new">+ มอบหมายงาน</PrimaryLink></>}/><section className="grid gap-4 sm:grid-cols-3"><StatCard label="งานทั้งหมด" value={assignments.length}/><StatCard label="การส่งงาน" value={submissions.length} tone="blue"/><StatCard label="งานล่าสุด" value={assignments[0]?.title??'-'} tone="orange"/></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-xl font-extrabold">รายการงาน</h2><p className="mt-1 text-sm text-slate-500">เลือกงานเพื่อดูรายละเอียดหรือตรวจงาน</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่องาน..." className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm sm:w-80"/></div>{error?<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>:null}<div className="mt-6">{!loading&&filtered.length===0?<EmptyState title="ยังไม่มีงาน" description="สร้างงานแรกเพื่อเริ่มใช้งานระบบ" action={<PrimaryLink href="/teacher/assignments/new">+ สร้างงาน</PrimaryLink>}/>:<div className="grid gap-4 lg:grid-cols-2">{filtered.map(a=><article key={a.id} className="rounded-2xl border border-slate-200 p-5 hover:border-orange-200 hover:shadow-md"><StatusBadge tone="orange">งานที่มอบหมาย</StatusBadge><h3 className="mt-3 truncate text-lg font-extrabold">{a.title}</h3><p className="mt-1 line-clamp-2 min-h-10 text-sm text-slate-500">{a.description||'ไม่มีรายละเอียดเพิ่มเติม'}</p><div className="mt-4 grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><div><p className="text-xs font-bold text-slate-400">กำหนดส่ง</p><p className="mt-1 font-bold">{formatDateTime(a.due_date)}</p></div><div><p className="text-xs font-bold text-slate-400">คะแนนเต็ม</p><p className="mt-1 font-bold">{a.max_score}</p></div></div><div className="mt-4 flex items-center justify-between gap-3"><div><p className="text-xs text-slate-400">ส่งแล้ว</p><p className="font-extrabold">{count.get(a.id)??0} งาน</p></div><div className="flex gap-2"><Link href={`/teacher/assignments/${a.id}`} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold">รายละเอียด</Link><Link href={`/teacher/submissions?assignment=${a.id}`} className="rounded-xl bg-slate-950 px-3 py-2 text-sm font-bold text-white">ตรวจงาน</Link></div></div></article>)}</div>}</div></section></div>
}
